---
- name: Install haproxy
  apt:
    name: haproxy
    state: present
    update_cache: yes

- name: Check for SSL cert
  stat:
    path: /etc/ssl/private/server.pem
  register: key

- name: create self-signed SSL cert
  command: openssl req -new -nodes -x509 -subj "/C=US/ST=Oregon/L=Portland/O=IT/CN={{ hostvars.localhost.haproxy.openstack.public_v4 }}" -days 365 -keyout /etc/ssl/private/server.key -out /etc/ssl/private/server.crt
  when: key.stat.exists == False

- name: create pem file
  shell: "cat /etc/ssl/private/server.crt /etc/ssl/private/server.key > /etc/ssl/private/server.pem"
  when: key.stat.exists == False
  notify:
    - restart haproxy

- name: Configure haproxy
  template:
    dest: "/etc/haproxy/haproxy.cfg"
    src: "haproxy.cfg.j2"
    owner: "root"
  notify:
    - restart haproxy

- name: enable haproxy service
  service:
    name: haproxy
    enabled: yes
