---
- name: set MySQL password before installation
  debconf:
    name: 'mysql-server'
    question: 'mysql-server/root_password'
    value: '{{ mysql.root_pass }}'
    vtype: 'password'

- name: set MySQL password confirmation before installation
  debconf:
    name: 'mysql-server'
    question: 'mysql-server/root_password_again'
    value: '{{ mysql.root_pass }}'
    vtype: 'password'

- name: install mysql
  apt:
    name: mysql-server
    state: present
    update_cache: yes

- name: install python-mysqldb
  apt:
    name: python-mysqldb
    state: present

- name: configure bind address
  replace:
    path: "/etc/mysql/mysql.conf.d/mysqld.cnf"
    regexp: '^bind-address\s+=.*'
    replace: "bind-address		= 0.0.0.0"
  notify:
    - restart mysql

- name: enable and start mysql service
  service:
    name: mysql
    state: started
    enabled: yes

- name: create mysql database for the app
  mysql_db:
    login_user: root
    login_password: "{{ mysql.root_pass }}"
    state: present
    name: "{{ app.db_name }}"

- name: create mysql user for the app
  mysql_user:
    login_user: root
    login_password: "{{ mysql.root_pass }}"
    state: present
    name: "{{ app.db_user }}"
    password: "{{ app.db_pass }}"
    priv: "{{ app.db_name }}.*:ALL"
    host: "%"
